name: Khan
description: Khan Framework
avatar: https://i.imgur.com/1KqeNw6.png
theme: jekyll-theme-cayman
footer-links:
  email: jskhanframework@gmail.com
  facebook: https://facebook.com/PauloRodriguesYT
  github: PaulaoDev/khan
