name: Khan Framework PHP
description: Khan Framework
avatar: "https://i.imgur.com/1KqeNw6.png"
theme: jekyll-theme-cayman
timezone: "America/SaoPaulo"
markdown: kramdown
highlighter: rouge
link-tags: true

author:
  name: PaulaoDev

kramdown:
  input: GFM
  
share-links-active:
  twitter: true
  facebook: true
  google: false
  linkedin: true

social-network-links:
  email: "jskhanframework@gmail.com"
  facebook: "https://facebook.com/PauloRodriguesYT"
  github: PaulaoDev
